# Generated by Django 4.2.15 on 2024-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='services', verbose_name='Imágen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado: ')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado: ')),
            ],
            options={
                'verbose_name': 'servicios',
                'verbose_name_plural': 'servicios',
                'ordering': ['-created'],
            },
        ),
    ]
